version: "3.8"

volumes:
  parahyba-valley-node-modules:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: sh -c 'while true; do sleep 60; done'
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - .:/app
      - parahyba-valley-node-modules:/app/node_modules
